// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package bwbvrlt.model;

import bwbvrlt.model.Rlt;
import bwbvrlt.model.RltDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RltDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RltDataOnDemand: @Component;
    
    private Random RltDataOnDemand.rnd = new SecureRandom();
    
    private List<Rlt> RltDataOnDemand.data;
    
    public Rlt RltDataOnDemand.getNewTransientRlt(int index) {
        Rlt obj = new Rlt();
        setDatum(obj, index);
        setKategorie(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void RltDataOnDemand.setDatum(Rlt obj, int index) {
        Date datum = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDatum(datum);
    }
    
    public void RltDataOnDemand.setKategorie(Rlt obj, int index) {
        String kategorie = "ka_" + index;
        if (kategorie.length() > 4) {
            kategorie = kategorie.substring(0, 4);
        }
        obj.setKategorie(kategorie);
    }
    
    public void RltDataOnDemand.setName(Rlt obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Rlt RltDataOnDemand.getSpecificRlt(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Rlt obj = data.get(index);
        Long id = obj.getId();
        return Rlt.findRlt(id);
    }
    
    public Rlt RltDataOnDemand.getRandomRlt() {
        init();
        Rlt obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Rlt.findRlt(id);
    }
    
    public boolean RltDataOnDemand.modifyRlt(Rlt obj) {
        return false;
    }
    
    public void RltDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Rlt.findRltEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Rlt' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Rlt>();
        for (int i = 0; i < 10; i++) {
            Rlt obj = getNewTransientRlt(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
