// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package bwbvrlt.model;

import bwbvrlt.model.RltErgebnis;
import bwbvrlt.model.RltErgebnisDataOnDemand;
import bwbvrlt.model.RltErgebnisIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RltErgebnisIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RltErgebnisIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RltErgebnisIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RltErgebnisIntegrationTest: @Transactional;
    
    @Autowired
    private RltErgebnisDataOnDemand RltErgebnisIntegrationTest.dod;
    
    @Test
    public void RltErgebnisIntegrationTest.testCountRltErgebnises() {
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to initialize correctly", dod.getRandomRltErgebnis());
        long count = RltErgebnis.countRltErgebnises();
        Assert.assertTrue("Counter for 'RltErgebnis' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RltErgebnisIntegrationTest.testFindRltErgebnis() {
        RltErgebnis obj = dod.getRandomRltErgebnis();
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to provide an identifier", id);
        obj = RltErgebnis.findRltErgebnis(id);
        Assert.assertNotNull("Find method for 'RltErgebnis' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RltErgebnis' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RltErgebnisIntegrationTest.testFindAllRltErgebnises() {
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to initialize correctly", dod.getRandomRltErgebnis());
        long count = RltErgebnis.countRltErgebnises();
        Assert.assertTrue("Too expensive to perform a find all test for 'RltErgebnis', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RltErgebnis> result = RltErgebnis.findAllRltErgebnises();
        Assert.assertNotNull("Find all method for 'RltErgebnis' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RltErgebnis' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RltErgebnisIntegrationTest.testFindRltErgebnisEntries() {
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to initialize correctly", dod.getRandomRltErgebnis());
        long count = RltErgebnis.countRltErgebnises();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RltErgebnis> result = RltErgebnis.findRltErgebnisEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RltErgebnis' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RltErgebnis' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RltErgebnisIntegrationTest.testFlush() {
        RltErgebnis obj = dod.getRandomRltErgebnis();
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to provide an identifier", id);
        obj = RltErgebnis.findRltErgebnis(id);
        Assert.assertNotNull("Find method for 'RltErgebnis' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRltErgebnis(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RltErgebnis' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RltErgebnisIntegrationTest.testMergeUpdate() {
        RltErgebnis obj = dod.getRandomRltErgebnis();
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to provide an identifier", id);
        obj = RltErgebnis.findRltErgebnis(id);
        boolean modified =  dod.modifyRltErgebnis(obj);
        Integer currentVersion = obj.getVersion();
        RltErgebnis merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RltErgebnis' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RltErgebnisIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to initialize correctly", dod.getRandomRltErgebnis());
        RltErgebnis obj = dod.getNewTransientRltErgebnis(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RltErgebnis' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RltErgebnis' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RltErgebnisIntegrationTest.testRemove() {
        RltErgebnis obj = dod.getRandomRltErgebnis();
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RltErgebnis' failed to provide an identifier", id);
        obj = RltErgebnis.findRltErgebnis(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RltErgebnis' with identifier '" + id + "'", RltErgebnis.findRltErgebnis(id));
    }
    
}
