// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package bwbvrlt.model;

import bwbvrlt.model.RltSpieler;
import bwbvrlt.model.RltSpielerDataOnDemand;
import bwbvrlt.model.RltSpielerIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RltSpielerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RltSpielerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RltSpielerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RltSpielerIntegrationTest: @Transactional;
    
    @Autowired
    private RltSpielerDataOnDemand RltSpielerIntegrationTest.dod;
    
    @Test
    public void RltSpielerIntegrationTest.testCountRltSpielers() {
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to initialize correctly", dod.getRandomRltSpieler());
        long count = RltSpieler.countRltSpielers();
        Assert.assertTrue("Counter for 'RltSpieler' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RltSpielerIntegrationTest.testFindRltSpieler() {
        RltSpieler obj = dod.getRandomRltSpieler();
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to provide an identifier", id);
        obj = RltSpieler.findRltSpieler(id);
        Assert.assertNotNull("Find method for 'RltSpieler' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RltSpieler' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RltSpielerIntegrationTest.testFindAllRltSpielers() {
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to initialize correctly", dod.getRandomRltSpieler());
        long count = RltSpieler.countRltSpielers();
        Assert.assertTrue("Too expensive to perform a find all test for 'RltSpieler', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RltSpieler> result = RltSpieler.findAllRltSpielers();
        Assert.assertNotNull("Find all method for 'RltSpieler' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RltSpieler' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RltSpielerIntegrationTest.testFindRltSpielerEntries() {
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to initialize correctly", dod.getRandomRltSpieler());
        long count = RltSpieler.countRltSpielers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RltSpieler> result = RltSpieler.findRltSpielerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RltSpieler' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RltSpieler' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RltSpielerIntegrationTest.testFlush() {
        RltSpieler obj = dod.getRandomRltSpieler();
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to provide an identifier", id);
        obj = RltSpieler.findRltSpieler(id);
        Assert.assertNotNull("Find method for 'RltSpieler' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRltSpieler(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RltSpieler' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RltSpielerIntegrationTest.testMergeUpdate() {
        RltSpieler obj = dod.getRandomRltSpieler();
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to provide an identifier", id);
        obj = RltSpieler.findRltSpieler(id);
        boolean modified =  dod.modifyRltSpieler(obj);
        Integer currentVersion = obj.getVersion();
        RltSpieler merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RltSpieler' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RltSpielerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to initialize correctly", dod.getRandomRltSpieler());
        RltSpieler obj = dod.getNewTransientRltSpieler(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RltSpieler' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RltSpieler' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RltSpielerIntegrationTest.testRemove() {
        RltSpieler obj = dod.getRandomRltSpieler();
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RltSpieler' failed to provide an identifier", id);
        obj = RltSpieler.findRltSpieler(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RltSpieler' with identifier '" + id + "'", RltSpieler.findRltSpieler(id));
    }
    
}
