package aufzug1.ui;

import aufzug1.model.AufzugController;
import aufzug1.model.Etage;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.*;

/**
 *
 * @author Andy
 */
public class MainFrame extends javax.swing.JFrame {

    private AufzugController controller;
    private JPanel aufzugPanel;
    private JPanel aussenPanel;
    private JLabel jLabel1;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(AufzugController controller) {        
        this.controller = controller;
//        initComponents();
        initComponents2();
    }
        
    private void initComponents2() {
        int anzahlEtagen = controller.getData().getAnzahlEtagen();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new FlowLayout());

        aufzugPanel = new JPanel();
        aufzugPanel.setLayout(new GridLayout(anzahlEtagen+1, 1));

        jLabel1 = new JLabel();
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText(String.valueOf(controller.getData().getAktuelleEtagennr()));
        aufzugPanel.add(jLabel1);

        aussenPanel = new JPanel();
        aussenPanel.setLayout(new GridLayout(anzahlEtagen+1, 1));
        aussenPanel.add(new JLabel(""));
        
        for (int i = anzahlEtagen-1; i>=0; i--) {
            Etage etage = controller.getData().getEtage(i);
            aufzugPanel.add(getEtagenButton(etage));
            aussenPanel.add(getEtagenButton(etage));
        }

        getContentPane().add(aufzugPanel);
        getContentPane().add(aussenPanel);

        pack();
    }

    private JButton getEtagenButton(final Etage etage){
        JButton jButton = new JButton(etage.getLabel());
        jButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etage.setAngefordert(true);
            }
        });    
        return jButton;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
