// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package bwbvrlt.model;

import bwbvrlt.model.RltSpieler;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RltSpieler_Roo_Configurable {
    
    declare @type: RltSpieler: @Configurable;
    
}
